### ISSUE TITLE
missing unload event

### ISSUE THREAD

**Issue by publicocean0** [mdn/simple-shared-worker#3]
missing a lot of events for shared worker body. 
Same thing For a Message Port. onclose it not avaiilable in this object. 

How can i understand if a client port is not more available?

**Comment by chrisdavidmills** [comment]
Sorry for the late reply - I was on holiday last week. I'm just trying to understand what you are saying in this issue. Are you saying you think that there are event handlers that should be included on the SharedWorker object spec? Or are you saying that there are event handlers that do exist in the spec, that my code is missing?

As far as I understand it, a MessagePort is always available and open if its associated worker is still alive. Once a worker is closed (killed) using the close() method, the port is also killed. I'd imagine you could test for the existence of these objects using the standard if exists type test, e.g. if(myWorker) {} or if(myPort) {}.

Is this not the case?

**Comment by publicocean0** [comment]
a example not working .....

I tried to proxy a websocket connection. 
Open page( 1-th instance) : connection is established
open page (2-th or more instances) : it uses the same connection. 
All seams work correctly but this test doesnt work

Open page( 1-th instance) : connection is established
Reload the same istance(same page): it doesnt use the same connection , but creates another connection. Pratically when you navigate from a page to another ... it seams to recreate new connections. Shared workker seams be used just you have multiple instances active but not if you pass to instance to another.

**Comment by publicocean0** [comment]
another example working badly 

how broadcast events from websocket to ports ? using a array of ports connected
How to know when a port is disconnected ? it is possible from shared worker!!!! This is a bad example of class lifecycle. I need to send a message client is closing before client is closing .. A stupid block of code really.

**Comment by schalkneethling** [comment]
Hey @publicocean0! Thank you for opening this issue. We are combining some of our repositories to enable us to triage pull requests and issues more effectively. Therefore, this specific repository will be merged into the more prominent [dom-examples](https://github.com/mdn/dom-examples) repository. Please open a new issue if you still feel that this issue is relevant. Thank you.
